/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef GPDRONEMIB_H
#define GPDRONEMIB_H


typedef struct{
	char * descr;
	char * path;
}LIGHT_TABLE_ENTRY;

struct tb_entry{
	long index;
	char descr[256];
	long toggle;
};

/* function declarations */
void init_gpDroneMIB(void);
int sysTimeUpHandler(netsnmp_mib_handler *handler,
                     netsnmp_handler_registration *reginfo,
                     netsnmp_agent_request_info *reqinfo,
                     netsnmp_request_info *requests);
int instPosGpsLatitudeHandler(netsnmp_mib_handler *handler,
                     netsnmp_handler_registration *reginfo,
                     netsnmp_agent_request_info *reqinfo,
                     netsnmp_request_info *requests);
int instPosGpsLongitudeHandler(netsnmp_mib_handler *handler,
                     netsnmp_handler_registration *reginfo,
                     netsnmp_agent_request_info *reqinfo,
                     netsnmp_request_info *requests);
int instPosAltitudeHandler(netsnmp_mib_handler *handler,
		     netsnmp_handler_registration *reginfo,
		     netsnmp_agent_request_info *reqinfo,
		     netsnmp_request_info *requests);
int instSpeedGroundHandler(netsnmp_mib_handler *handler,
		     netsnmp_handler_registration *reginfo,
		     netsnmp_agent_request_info *reqinfo,
		     netsnmp_request_info *requests);
int instSpeedVerticalHandler(netsnmp_mib_handler *handler,
		     netsnmp_handler_registration *reginfo,
		     netsnmp_agent_request_info *reqinfo,
		     netsnmp_request_info *requests);
int instTotalFuelHandler(netsnmp_mib_handler *handler,
		     netsnmp_handler_registration *reginfo,
		     netsnmp_agent_request_info *reqinfo,
		     netsnmp_request_info *requests);
int instClTimeHandler(netsnmp_mib_handler *handler,
		     netsnmp_handler_registration *reginfo,
		     netsnmp_agent_request_info *reqinfo,
		     netsnmp_request_info *requests);
int lgSetPositionHandler(netsnmp_mib_handler *handler,
		     netsnmp_handler_registration *reginfo,
		     netsnmp_agent_request_info *reqinfo,
		     netsnmp_request_info *requests);
void runGetScript(const char * arg);
void fetch_integer(const char * arg, long * var);
void fetch_string_of_float(const char * arg, char * var);
void fetch_string(const char * arg, char * var);


/*tabulars...*/
/* function declarations */
void init_gpDroneMIB(void);
void initialize_table_lightingTable(void);
Netsnmp_Node_Handler lightingTable_handler;

/* column number definitions for table lightingTable */
/*       #define COLUMN_LIGHTDESCRIPTION		1
       #define COLUMN_LIGHTTOGGLE		2
       #define COLUMN_LIGHTINDEX		3
*/
       #define COLUMN_LIGHTINDEX		1
       #define COLUMN_LIGHTDESCRIPTION		2
       #define COLUMN_LIGHTTOGGLE		3


#endif /* GPDRONEMIB_H */
