/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "gpDroneMIB.h"

/** Initialize the lightingTable table by defining its contents and how it's structured */
void
initialize_table_lightingTable(void)
{
    const oid lightingTable_oid[] = {1,3,6,1,4,1,12620,5,2};
    netsnmp_table_data_set *table_set;

    /* create the table structure itself */
    table_set = netsnmp_create_table_data_set("lightingTable");

    /* comment this out or delete if you don't support creation of new rows */
    table_set->allow_creation = 1;

    /***************************************************
     * Adding indexes
     */
    DEBUGMSGTL(("initialize_table_lightingTable",
                "adding indexes to table lightingTable\n"));
    netsnmp_table_set_add_indexes(table_set,
                           ASN_INTEGER,  /* index: lightIndex */
                           0);

    DEBUGMSGTL(("initialize_table_lightingTable",
                "adding column types to table lightingTable\n"));		 
    netsnmp_table_set_multi_add_default_row(table_set,
                                            COLUMN_LIGHTDESCRIPTION, ASN_OCTET_STR, 0,
                                            NULL, 0,
                                            COLUMN_LIGHTTOGGLE, ASN_INTEGER, 1,
                                            NULL, 0,
                                            COLUMN_LIGHTINDEX, ASN_INTEGER, 0,
                                            NULL, 0,
                              0);
    
    /* registering the table with the master agent */
    /* note: if you don't need a subhandler to deal with any aspects
       of the request, change lightingTable_handler to "NULL" */
    netsnmp_register_table_data_set(netsnmp_create_handler_registration("lightingTable", lightingTable_handler,
                                                        lightingTable_oid,
                                                        OID_LENGTH(lightingTable_oid),
                                                        HANDLER_CAN_RWRITE),
                            table_set, NULL);
	netsnmp_table_row *row;
	long index = 1;
	row = netsnmp_create_table_data_row();
	netsnmp_table_row_add_index(row,ASN_INTEGER,index,sizeof(index));
	netsnmp_set_row_column(row,1,ASN_OCTET_STR,"My ass light, that is what it is...",strlen("My ass light, that is what it is..."));
	netsnmp_mark_row_column_writable(row,1,0);
	netsnmp_set_row_column(row,1,ASN_INTEGER,(int)index,4);
	netsnmp_mark_row_column_writable(row,2,0);
	netsnmp_table_dataset_add_row(table_set,row);
	//netsnmp_register_auto_data_table(table_set,NULL);
}

/** Initializes the gpDroneMIB module */
void
init_gpDroneMIB(void)
{

  /* here we initialize all the tables we're planning on supporting */
    initialize_table_lightingTable();
}


/** handles requests for the lightingTable table, if anything else needs to be done */
int
lightingTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {
    /* perform anything here that you need to do.  The requests have
       already been processed by the master table_dataset handler, but
       this gives you chance to act on the request in some other way
       if need be. */
    return SNMP_ERR_NOERROR;
}
